#pragma once
// Copyright (c) 2026 IEX Matching Engine Project
// Matching engine — routes orders to per-symbol books, drives price-time
// priority matching, and emits TradeEvents.
//
// Threading: single-threaded. The sequencer (Phase 2) is the sole writer;
// all calls to submit() and cancel() come from one thread. No locks needed.
//
// Memory: the OrderPool and pending_trades_ vector are pre-allocated at
// construction. No heap allocation occurs on the hot path after startup.

#include "engine/order_book.hpp"
#include "engine/order_pool.hpp"
#include "engine/types.hpp"

#include <flat_map>
#include <optional>
#include <span>
#include <vector>

namespace iex {

class MatchingEngine {
public:
    // Maximum trade events buffered per submit() call. A single aggressive
    // order can fill against many resting orders; 1024 covers any realistic
    // sweep. pending_trades_ is reserved to this size at construction so
    // push_back never allocates on the hot path.
    static constexpr std::size_t kMaxTradesPerSubmit = 1'024;

    // Default pool capacity: 1,000,000 × 64 B = 64 MB.
    static constexpr std::size_t kDefaultPoolCapacity = 1'000'000;

    explicit MatchingEngine(
        std::size_t pool_capacity = kDefaultPoolCapacity);

    // Non-copyable and non-movable: owns the pool and all live Order pointers.
    MatchingEngine(const MatchingEngine&)            = delete;
    MatchingEngine& operator=(const MatchingEngine&) = delete;
    MatchingEngine(MatchingEngine&&)                 = delete;
    MatchingEngine& operator=(MatchingEngine&&)      = delete;

    // Register a symbol before trading begins. Must be called during
    // initialisation, before any submit() calls for that symbol.
    // Not thread-safe; call only from the setup thread.
    void register_symbol(SymbolId symbol);

    // Submit an order. On success returns the assigned OrderId.
    // Market orders and IOC orders that cannot be fully filled have their
    // remainder cancelled; only limit orders rest in the book.
    //
    // Errors:
    //   kInvalidQuantity  — qty == 0
    //   kInvalidPrice     — price <= 0 for a limit order
    //   kUnknownSymbol    — symbol was not registered
    //   kPoolExhausted    — no free Order slots remain
    [[nodiscard]] std::expected<OrderId, EngineError> submit(
        SymbolId   symbol,
        Side       side,
        OrderType  type,
        Price      price,
        Quantity   qty) noexcept;

    // Cancel a resting order. Returns kOrderNotFound if id is unknown or stale.
    [[nodiscard]] std::expected<void, EngineError> cancel(
        OrderId id) noexcept;

    // Return the trade events generated by the most recent submit() call.
    // The span is valid until the next submit() call (which clears the buffer).
    [[nodiscard]] std::span<const TradeEvent> drain_trades() noexcept;

    // Query the best bid/offer for a symbol.
    // Returns std::nullopt if the symbol is not registered.
    [[nodiscard]] std::optional<BestBidOffer> get_bbo(
        SymbolId symbol) const noexcept;

private:
    // Walk the passive side of `book`, filling `aggressor` at each level
    // (FIFO within level) until it is fully filled or no more crosses exist.
    // Freed passive Orders are returned to pool_ immediately.
    // Emitted TradeEvents are appended to pending_trades_.
    void match_order(OrderBook& book, Order* aggressor) noexcept;

    OrderPool pool_;

    // One OrderBook per registered symbol. Pre-populated by register_symbol();
    // not modified on the hot path (no new symbol insertions during trading).
    std::flat_map<SymbolId, OrderBook> books_;

    // Trade event buffer. Cleared at the start of each submit(); callers
    // drain via drain_trades() before the next submit() if they need events.
    std::vector<TradeEvent> pending_trades_;
};

} // namespace iex
